services:
  - type: web
    name: money-matrix
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:main
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: DATABASE_URI
        sync: false